### Variables
@baseUrl = http://localhost:8081
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjIxN2M4MDFlZjliYTc0YWExMmU3YiIsImVtYWlsIjoiYWRtaW4zQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJhZG1pbl91c2VyIiwiaWF0IjoxNzI3Mjg5NzM1LCJleHAiOjE3MjcyOTMzMzV9.wj0HQk6TPZbackClR15NflxXvlvyfZvXcXC_q-PJU2k
@productId = your_product_id_here

###
POST http://localhost:8081/recipe/add
Content-Type: application/json

{
  "title": "Vanilla Cake",
  "recipe": "A lovely vanilla cake.",
  "imageData": "base64encodedstring",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 tsp vanilla", "2 eggs", "1 cup milk", "1 tsp vanilla bean"],
  "instructions": "Mix all ingredients and bake at 350°F for 30 minutes."
}

###
PUT {{baseUrl}}}}/recipe/update/66e310f6717e50c6e609a5eb
Content-Type: application/json

{
  "title": "Updated Chocolate Cake",
  "recipe": "An updated delicious chocolate cake recipe.",
  "imageData": "updatedbase64encodedstring",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 cup cocoa powder", "2 eggs", "1 cup milk"],
  "instructions": "Mix all ingredients and bake at 350°F for 35 minutes."
}

###
POST http://localhost:8081/recipe/add
Content-Type: application/json

{
  "title": "Cheesecake",
  "recipe": "A delicious cheesecake recipe.",
  "imageData": "anotherbase64encodedstring",
  "ingredients": ["2 cups flour", "1 cup sugar", "1 cup cocoa powder", "2 eggs"],
  "instructions": "Mix all ingredients and bake at 350°F for 30 minutes."
}

###
# Create a new product
POST http://localhost:8081/products
Content-Type: application/json

{
  "name": "Chocolate Cake",
  "description": "A delicious chocolate cake with banana.",
  "price": 18.99,
  "imgName": "construction.png",
  "category": "Test Category"
}

###
# Get all products
GET http://localhost:8081/products

###
# Get a single product by ID
# Replace <product_id> with the actual product ID after creating a product
GET http://localhost:8081/products/<product_id>

###
# Update a product by ID
# Replace <product_id> with the actual product ID after creating a product
PUT http://localhost:8081/products/<product_id>
Content-Type: application/json

{
  "name": "Updated Test Product",
  "description": "This is an updated test product",
  "price": 12.99,
  "imageUrl": "http://example.com/updated_image.jpg",
  "category": "Updated Test Category"
}

###
# Delete a product by ID
# Replace <product_id> with the actual product ID after creating a product
DELETE http://localhost:8081/products/66e3a720798a1ed2a079968e

### Create Admin User
POST http://localhost:8081/users/register
Content-Type: application/json

{
  "username": "admin_user",
  "email": "admin3@example.com",
  "password": "AdminPass123!",
  "isAdmin": true
}

### Create Regular User
POST http://localhost:8081/users/register
Content-Type: application/json

{
  "username": "regular_user1",
  "email": "user1@example.com",
  "password": "UserPass123!"
}

###

### Login as Admin
POST http://localhost:8081/users/login
Content-Type: application/json 

{
    "username": "admin_user",
    "password": "AdminPass123!"
}

###

### Login as Regular User
POST http://localhost:8081/users/login
Content-Type: application/json 

{
    "username": "regular_user1",
    "password": "UserPass123!"
}

###

### Get All Users (Admin only)
GET {{baseUrl}}}}/users/all
Authorization: Bearer {{authToken}}

###

### Edit User (Replace :id with actual user id)
PUT http://localhost:8081/users/edit/:id
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
    "username": "updated_username",
    "email": "updated@example.com"
}

###

### Delete User (Replace :id with actual user id)
DELETE http://localhost:8081/users/delete/66e8f12285f1e775bca6bda5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZThmMThkODVmMWU3NzViY2E2YmRhYyIsImVtYWlsIjoiYWRtaW4zQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJhZG1pbl91c2VyIiwiaWF0IjoxNzI2NTQyODEyLCJleHAiOjE3MjY1NDY0MTJ9.O2ofBsff9UJ503DcKq5fmVtYceBsRiWhl3OHWXUMA_0

###

### Get User Profile
GET http://localhost:8081/users/profile
Authorization: Bearer YOUR_TOKEN_HERE

###

### Change Password
PUT http://localhost:8081/users/change-password
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
    "oldPassword": "UserPass123!",
    "newPassword": "NewUserPass456!"
}

###



### Retrieve all images
GET http://localhost:8081/api/images
Content-Type: application/json

### Retrieve image by name
GET http://localhost:8081/api/getByName/imageTest.png
Content-Type: application/json

### Retrieve image by imgUrl
GET http://localhost:8081/api/getByUrl?imgUrl=https://firebasestorage.googleapis.com/v0/b/bakeryapp-a05a3.appspot.com/o/Construction.png
Content-Type: application/json



### Get all products
GET {{baseUrl}}/products

### Get a single product
GET {{baseUrl}}/products/product_id_here

### Create a new product (Admin only)
POST {{baseUrl}}/products
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Carrot Cake",
  "description": "Spiced carrot cake with cream cheese frosting.",
  "price": 17.99,
  "category": "Cakes",
  "imageId": "66f220650036faf320bca9d0",
  "ingredients": ["Flour", "Sugar", "Butter", "Carrots", "Eggs", "Walnuts"],
  "allergens": ["Wheat", "Dairy", "Eggs", "Nuts"],
  "inStock": true,
  "quantity": 50
}

### Update a product (Admin only)
PUT {{baseUrl}}/products/66f2187f01ef9ba74aa12e7e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjIxN2M4MDFlZjliYTc0YWExMmU3YiIsImVtYWlsIjoiYWRtaW4zQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJhZG1pbl91c2VyIiwiaWF0IjoxNzI3MTQxODMyLCJleHAiOjE3MjcxNDU0MzJ9.iD10DK_VyjIJs6jcOyQ0DOgB-NjiymmsBDcbsOWuMOo
Content-Type: application/json

{
  "name": "Chocolate Cake",
  "price": 6.99,
  "quantity": 40
}

### Delete a product (Admin only)
DELETE {{baseUrl}}/products/product_id_here
Authorization: Bearer {{authToken}}

###

# Add Item to Cart
POST {{baseUrl}}/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjQ1ZjUxYTMxOWI0MDhhNTNmMDg4NiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InJlZ3VsYXJfdXNlcjEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzI3MjkxMjE4LCJleHAiOjE3MjcyOTQ4MTh9.-T4-NMdG9P99E4hLdqUHU7EHSTa9L3SBtZaT3jU-Ulo

{
  "productId": "66f2187f01ef9ba74aa12e7e",
  "quantity": 2
}

###

# Get Current User's Cart
GET {{baseUrl}}/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjQ1ZjUxYTMxOWI0MDhhNTNmMDg4NiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InJlZ3VsYXJfdXNlcjEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzI3MjkxMjE4LCJleHAiOjE3MjcyOTQ4MTh9.-T4-NMdG9P99E4hLdqUHU7EHSTa9L3SBtZaT3jU-Ulo

###

# Update Item Quantities in Cart
PUT {{baseUrl}}/cart/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjQ1ZjUxYTMxOWI0MDhhNTNmMDg4NiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InJlZ3VsYXJfdXNlcjEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzI3MjkxMjE4LCJleHAiOjE3MjcyOTQ4MTh9.-T4-NMdG9P99E4hLdqUHU7EHSTa9L3SBtZaT3jU-Ulo

{
  "items": [
    {
      "productId": "66f2187f01ef9ba74aa12e7e",
      "quantity": 3
    }
    // Add more items as needed
  ]
}

###

# Remove an Item from the Cart
DELETE {{baseUrl}}/cart/remove/{{productId}}
Authorization: Bearer {{authToken}}

###

# Clear the Cart
DELETE {{baseUrl}}/cart/clear
Authorization: Bearer {{authToken}}

###